catho/quantum

components/Slider/__snapshots__/Slider.unit.test.jsx.snap, components/Tooltip/Tooltip.jsx, components/Tooltip/Tooltip.unit.test.jsx, components/Tooltip/__snapshots__/Tooltip.unit.test.jsx.snap, components/Tooltip/options.js, stories/Slider/Slider.story.jsx, stories/Tooltip/Tooltip.story.jsx
Tooltip was causing maximum depth update exceeded, so we made some improvements.
=> [BTS-179] Fix: Tooltip state management

stories/Dropdown/Dropdown.story.jsx
Updated the _Dropdown_ import of your story.
=> Update Dropdown story

package.json, stories/Colors/Colors.jsx, stories/Dropdown/Dropdown.story.jsx, stories/Form/Form.story.jsx, stories/Grid/Grid.jsx, stories/Icon/Icon.story.jsx, stories/Introduction/Introduction.jsx, stories/RadioGroup/RadioGroup.story.jsx, stories/Slider/Slider.story.jsx, yarn.lock
Updating quantum-storybook-ui and improving some stories
=> [BTS-194] Dependencies and docs

components/Grid/sub-components/Container.jsx, stories/Grid/Grid.jsx
=> [BTS-240] Container fix

components/Form/__snapshots__/Form.unit.test.jsx.snap, components/Input/Input.jsx, components/Input/Input.unit.test.jsx, components/Input/__snapshots__/Input.unit.test.jsx.snap
=> fix(Input): Icons positioning

components/Form/Form.jsx, components/Form/Form.unit.test.jsx, stories/Form/Form.story.jsx
=> fix(Form): Change "onChange" parameters

components/Input/Input.jsx, components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
=> Input: turn off number input spinner

components/Alert/Alert.jsx, components/Alert/Alert.unit.test.jsx, components/Alert/__snapshots__/Alert.unit.test.jsx.snap, components/SnackBar/__snapshots__/SnackBar.unit.test.jsx.snap, components/shared/theme.js
Alert component featuring themification
=> [BTS-315] - Alert

components/GlobalStyle/test.utils.js, components/shared/index.js, components/shared/shadow.js, components/shared/shadow.unit.test.js
=> [BTS-390] SHADOW NOW Helper

components/Alert/Alert.jsx
using destructed sizes instead of imported ones
=> [BTS-315] Alert

components/Toggle/Toggle.jsx, components/Toggle/__snapshots__/Toggle.unit.test.jsx.snap
https://jirasoftware.catho.com.br/browse/BTS-279
=> [BTS-279] Themification: Toggle

components/GlobalStyle/sub-components/IconFont.jsx, components/GlobalStyle/sub-components/IconFont.unit.test.jsx, components/GlobalStyle/sub-components/Typography.jsx
=> Adding new parameter in Google Fonts url

components/Slider/Slider.jsx, components/Slider/__snapshots__/Slider.unit.test.jsx.snap, stories/Slider/Slider.story.jsx, stories/Slider/examples/BasicDisabled.jsx, stories/Slider/examples/index.js
https://jirasoftware.catho.com.br/browse/BTS-280
=> [BTS-280-slider] Theming: Slider

components/List/sub-components/__snapshots__/Item.unit.test.jsx.snap, components/Modal/__snapshots__/Modal.unit.test.jsx.snap, components/Popover/__snapshots__/Popover.unit.test.jsx.snap, components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap, components/shared/shadow.unit.test.js
Updates the tests snapshots.
run `npm run test`
=> fix: updates snapshots

components/List/sub-components/__snapshots__/Item.unit.test.jsx.snap, components/Modal/__snapshots__/Modal.unit.test.jsx.snap, components/Popover/__snapshots__/Popover.unit.test.jsx.snap, components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
This PR fixes master branch out of date snapshots.
=> fix: Fixes out of date snapshots

yarn.lock
=> fix: Eslint critical warning

docs/PULL_REQUEST_TEMPLATE.md
creates a pull request template.
=> docs: Pull request template

stories/SnackBar/SnackBar.story.jsx, stories/SnackBar/examples/SnackBarExampleError.jsx, stories/SnackBar/examples/SnackBarExamplePrimary.jsx, stories/SnackBar/examples/SnackBarExampleSuccess.jsx, stories/SnackBar/examples/index.js
Adds examples to SnackBar stories.
=> feat(snackbar): adds examples to snackbar stories

.storybook/manager-head.html
Removes the error below from console in storybook.
=> fix(manager-head): removes console warning in storybook

.travis.yml, package.json
=> Revert "Feat/regression tests on ci"

docs/PULL_REQUEST_TEMPLATE.md
update the description of pull request template
=> chore(pull-request-template): update the description of pull request template

.storybook/stories.js, stories/Breakpoints/Breakpoints.story.jsx
https://jirasoftware.catho.com.br/browse/QTM-90
=> docs(breakpoints): create docs for breakpoints implementation

components/Pagination/Pagination.jsx
https://jirasoftware.catho.com.br/browse/QTM-163
- yarn build on this branch
- overwrite `quantum-react-examples` node_modules/@catho/quantum with it
- yarn dev
- open quantum page and reload, it should load fine.
=> fix: Fixes pagination window verification

components/Dropdown/Dropdown.jsx, components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap
https://jirasoftware.catho.com.br/browse/QTM-160
=> fix(Dropdown): Fixes autocomplete typing filter

components/Accordion/index.d.ts, components/Alert/index.d.ts, components/Button/index.d.ts, components/Checkbox/index.d.ts, components/GlobalStyle/index.d.ts, components/Grid/index.d.ts, components/Hamburger/index.d.ts, components/Icon/index.d.ts, components/Input/index.d.ts, components/Modal/index.d.ts, components/Pagination/index.d.ts, components/Popover/index.d.ts, components/ProgressBar/index.d.ts, components/RadioGroup/index.d.ts, components/RangeSlider/index.d.ts, components/Skeleton/index.d.ts, components/SnackBar/index.d.ts, components/Socials/index.d.ts, components/TabbedView/index.d.ts, components/Tag/index.d.ts, components/TextArea/index.d.ts, components/Toggle/index.d.ts, components/Tooltip/index.d.ts, components/index.d.ts
=> AUTH-164: Issue #189

components/SocialButton/index.d.ts, components/index.d.ts, components/index.js
Enabling SocialButton importing from the project root and removed the title property
=> fix(SocialButton): Added SocialButton to index.js

components/SnackBar/SnackBar.jsx, components/SnackBar/index.d.ts, stories/SnackBar/SnackBar.story.jsx, stories/SnackBar/examples/SnackBarExampleCallback.jsx, stories/SnackBar/examples/index.js
https://jirasoftware.catho.com.br/browse/QTM-169
=> fix(Snackbar): Fixes a component prop name

stories/Icon/Icon.story.jsx
https://jirasoftware.catho.com.br/browse/QTM-181
=> Doc(Icons): Add info when the Icon is implemented in the earlier way 

stories/Button/Button.story.jsx
=> docs(Button): replace icons examples for icons of the catalog

components/Alert/Alert.jsx, components/Alert/__snapshots__/Alert.unit.test.jsx.snap, components/Badge/__snapshots__/Badge.unit.test.jsx.snap, components/Button/Button.jsx, components/Button/__snapshots__/Button.unit.test.jsx.snap, components/Checkbox/__snapshots__/CheckboxGroup.unit.test.jsx.snap, components/Dropdown/Dropdown.jsx, components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap, components/Form/__snapshots__/Form.unit.test.jsx.snap, components/Input/Input.jsx, components/Input/__snapshots__/Input.mask.unit.test.jsx.snap, components/Modal/__snapshots__/Modal.unit.test.jsx.snap, components/Popover/__snapshots__/Popover.unit.test.jsx.snap, components/RadioGroup/__snapshots__/RadioButton.unit.test.jsx.snap, components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap, components/SocialButton/__snapshots__/SocialButton.unit.test.jsx.snap, components/Tag/Tag.jsx, components/Tag/__snapshots__/Tag.unit.test.jsx.snap
when the page is loading, the Icon shows bigger then your normal.
It occurs cause the Icon loads before the CSS of material.
to test the changes:
- download the branch and build Quantum: `yarn build`
- copy the content of the quantum builded to your application:
`cp -R dist/* <YOUR_APP_PATH>/node_modules/@catho/quantum/`
- start your application and review if the behavior sounds right.
=> fix(Icon): Fixes the Icon loading 

components/Modal/index.d.ts
Adding types to `<Modal />` component.
**Issue:** #219
=> Adding types to <Modal />

components/TabbedView/index.d.ts
The Tabbedview component was update with a new prop `onClick`. This PR updates the typescript interface that component, that it was missed.
=> fix(Tabbedview): update ts interface of component

components/Accordion/__snapshots__/Accordion.unit.test.jsx.snap, components/Alert/__snapshots__/Alert.unit.test.jsx.snap, components/Button/__snapshots__/Button.unit.test.jsx.snap, components/Checkbox/__snapshots__/Checkbox.unit.test.jsx.snap, components/Checkbox/__snapshots__/CheckboxGroup.unit.test.jsx.snap, components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap, components/GlobalStyle/sub-components/Typography.jsx, components/Icon/Icon.jsx, components/Icon/__snapshots__/Icon.unit.test.jsx.snap, components/Input/__snapshots__/Input.mask.unit.test.jsx.snap, components/Modal/__snapshots__/Modal.unit.test.jsx.snap, components/Popover/__snapshots__/Popover.unit.test.jsx.snap, components/RadioGroup/__snapshots__/RadioButton.unit.test.jsx.snap, components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap, components/Tag/__snapshots__/Tag.unit.test.jsx.snap, components/Toggle/__snapshots__/Toggle.unit.test.jsx.snap
This PR, improve the render and retires styled-component of inside of the component.
=> feat(Icon): removes styled-component from component to optimize render

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-199
=> feat(Icon): adds new Icon to catalogue

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/submit-request.md
As improvements to create a new issues in this repo, I created a _ISSUE_TEMPLATE_ to automatize this process. 
You can see this process in the image below:
It was created based on [Github CLI repo](https://github.com/cli/cli/tree/trunk/.github)
=> Creating ISSUE_TEMPLATE

components/Input/Input.jsx, components/Input/Input.unit.test.jsx
Reverts catho/quantum#266
need to resolve conflicts with `<Form />` before this merge.
This PR is allright, but the Form componente should be fixed before this implementation.
=> Revert "fix(Input): update state when value prop is changed"

stories/Avatar/Avatar.story.jsx
=> fix(Avatar): update component description

package.json
=> fix(storybook deployer): updates deploy-storybook config

.github/workflows/actions-publish.yml, package.json
=> fix(storybook deployer): implements deploy storybook in yml

stories/Avatar/Avatar.story.jsx
=> fix(Avatar): updates doc

.github/workflows/actions-publish.yml
=> ci(deploy to ghpages): add new github_token in publish yml

.github/workflows/actions-publish.yml
=> ci(deploy to ghpages): implements both github tokens

stories/Socials/Socials.story.jsx
=> docs(Socials): updates doc description

components/Form/Form.jsx, components/Form/Form.unit.test.jsx, stories/Form/AdvancedValidation.jsx
recursively validate form's children
fix #190
=> fix(form): form validation fix

stories/Tag/TagExamples.jsx
https://jirasoftware.catho.com.br/browse/QTM-195
=> fix(Tags): corrige props passadas no componente

components/Stepper/index.d.ts, components/index.d.ts
Creating `<Stepper />` types to use in Typescript projects.
=> [Fix]: Creating Stepper types

docs/PULL_REQUEST_TEMPLATE.md
- adds a11y and TypeScript checks
- removes IE11 check.
=> docs(pull request template): updates pr template

stories/SegmentedControl/SegmentedControl.story.jsx
=> feat(Segmented control): updates doc

package.json, yarn.lock
This PR updates commitizen for securiy issues reported here: https://github.com/catho/quantum/security/dependabot/yarn.lock/merge/open
=> chore(Security updates): updates commitizen

stories/Socials/examples/SocialExampleWithoutBox.jsx, stories/Socials/examples/SocialExampleWithoutBoxChangingSize.jsx
https://jirasoftware.catho.com.br/browse/QTM-145
=> docs(Socials component): updates demonstration code

.github/workflows/actions-development.yml, .github/workflows/actions-publish.yml
=> chore(QTM-285): Updates SO on CI/CD

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-281
https://jirasoftware.catho.com.br/browse/QTM-287
=> feat(QTM-281): Adding missing icons for header

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-306
=> feat(QTM-306): Adding new launch icon

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-308
=> feat(QTM-308): Adding new icon - Cached 

docs/PULL_REQUEST_TEMPLATE.md
=> chore(A11y checks): adds new a11y checks for pull requests template

components/Modal/Modal.jsx, components/Modal/__snapshots__/Modal.unit.test.jsx.snap
https://jirasoftware.catho.com.br/browse/QTM-317
=> fix(modal): Improves Modal's overlap

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-319
=> feat(QTM-319): Adds location city icon

CONTRIBUTING.MD, package.json, scripts/create-component.js, scripts/templates/component-story.js, scripts/templates/component.js
Sets a script to generate initial structure for a new component
- `yarn generate COMPONENT_NAME`
=> chore(scripts): Sets component generator

components/Accordion/Accordion.jsx, components/Accordion/Accordion.unit.test.jsx, components/Accordion/__snapshots__/Accordion.unit.test.jsx.snap, components/Accordion/mock.jsx, components/Alert/Alert.unit.test.jsx, components/Alert/__snapshots__/Alert.unit.test.jsx.snap, components/Avatar/Avatar.unit.test.jsx, components/Avatar/__snapshots__/Avatar.unit.test.jsx.snap, package.json, yarn.lock
https://jirasoftware.catho.com.br/browse/QTM-322
=> Test(Qtm-322) Test migration - Enzyme to text-library: Accordion, Alert and Avatar

components/AutoComplete/AutoComplete.unit.test.jsx, components/AutoComplete/__snapshots__/AutoComplete.unit.test.jsx.snap, components/Badge/Badge.unit.test.jsx, components/Badge/__snapshots__/Badge.unit.test.jsx.snap, components/Button/Button.unit.test.jsx, components/Button/__snapshots__/Button.unit.test.jsx.snap, components/Card/Card.unit.test.jsx, components/Card/__snapshots__/Card.unit.test.jsx.snap, jest-config.js, package.json, yarn.lock
https://jirasoftware.catho.com.br/browse/QTM-323 + AutoComplete 
I added the user-event package to latter improve AutoComplete tests with arrow navigation tests.
=> Tests(Qtm-323)Migrating Badge, Button,Card and AutoComplete Unit tests

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/CCOM-279
=> feat(icon): Includes watch-later icon

stories/AutoComplete/AutoComplete.story.jsx, stories/Dropdown/Dropdown.story.jsx, stories/Dropdown/examples.jsx
=> docs(AutoComplete):Hiding old autocomplete prop and adding new AutoComplete to form story

components/Form/Form.unit.test.jsx, components/Form/__snapshots__/Form.unit.test.jsx.snap, components/Grid/sub-components/Container.unit.test.jsx, components/Grid/sub-components/Hide.unit.test.jsx, components/Grid/sub-components/__snapshots__/Container.unit.test.jsx.snap, components/Grid/sub-components/__snapshots__/Hide.unit.test.jsx.snap, components/Hamburger/Hamburger.jsx, components/Hamburger/Hamburger.unit.test.jsx, components/Hamburger/__snapshots__/Hamburger.unit.test.jsx.snap
https://jirasoftware.catho.com.br/browse/QTM-326
⚠️ I needed to fix a bug in the Hamburguer component, due to react testing library triggering a console error because of this bug.
=> Test(Qtm-326) - MIgrating Form, Grid and Hamburguer unit tests

components/Input/Input.jsx, components/Input/Input.unit.test.jsx
https://jirasoftware.catho.com.br/browse/QTM-335
=> fix(QTM-335): Fixing input bug with external value

components/Icon/Icon.unit.test.jsx, components/Icon/__snapshots__/Icon.unit.test.jsx.snap, components/Input/Input.mask.unit.test.jsx, components/Input/Input.unit.test.jsx, components/Input/__snapshots__/Input.mask.unit.test.jsx.snap, components/Input/sub-components/TextInput.unit.test.jsx, components/Input/sub-components/__snapshots__/TextInput.unit.test.jsx.snap, components/Link/Link.unit.test.jsx, components/Link/__snapshots__/Link.unit.test.jsx.snap, components/List/List.unit.test.jsx, components/List/__snapshots__/List.unit.test.jsx.snap, components/List/sub-components/Content.unit.test.jsx, components/List/sub-components/Header.unit.test.jsx, components/List/sub-components/Item.jsx, components/List/sub-components/Item.unit.test.jsx, components/List/sub-components/SubHeader.unit.test.jsx, components/List/sub-components/__snapshots__/Content.unit.test.jsx.snap, components/List/sub-components/__snapshots__/Header.unit.test.jsx.snap, components/List/sub-components/__snapshots__/Item.unit.test.jsx.snap, components/List/sub-components/__snapshots__/SubHeader.unit.test.jsx.snap
https://jirasoftware.catho.com.br/browse/QTM-328
⚠️ Needed to make a small fix in the Item component, inside list folder, to remove a console error.
The ajust was to generate a unit key in case multiple items.
=> Test(Qtm-328) - Migrating Icon, Input and List unit tests + Link

components/ProgressBar/ProgressBar.unit.test.jsx, components/ProgressBar/__snapshots__/ProgressBar.unit.test.jsx.snap, components/RadioGroup/RadioButton.unit.test.jsx, components/RadioGroup/RadioGroup.unit.test.jsx, components/RadioGroup/__snapshots__/RadioButton.unit.test.jsx.snap, components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap, components/RangeSlider/RangeSlider.jsx, components/RangeSlider/RangeSlider.unit.test.jsx, components/RangeSlider/__snapshots__/RangeSlider.unit.test.jsx.snap
https://jirasoftware.catho.com.br/browse/QTM-330
=> Tests(Qtm-330) - Migrating ProgressBar, Radiogroup and RangeSlider unit tests

components/Toggle/Toggle.unit.test.jsx, components/Toggle/__snapshots__/Toggle.unit.test.jsx.snap, components/Tooltip/Tooltip.jsx, components/Tooltip/Tooltip.unit.test.jsx, components/Tooltip/__snapshots__/Tooltip.unit.test.jsx.snap, components/shared/hooks/UseMaxWidthMediaQuery/useMaxWidthMediaQuery.unit.test.jsx
https://jirasoftware.catho.com.br/browse/QTM-334
- Toggle
- Tooltip
=> test(QTM-334): Migrates tests to testing library

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-337
=> feat(QTM-337): Adds trending up Icon

components/Form/Form.unit.test.jsx, components/Form/__snapshots__/Form.unit.test.jsx.snap, components/Form/index.d.ts, components/Form/validations.js
https://jirasoftware.catho.com.br/browse/QTM-336
=> Feat(QTM-336) - Adding new email validation

components/AutoComplete/AutoComplete.jsx, components/AutoComplete/AutoComplete.unit.test.jsx, components/AutoComplete/index.d.ts, stories/AutoComplete/AutoComplete.story.jsx
https://jirasoftware.catho.com.br/browse/CCOM-280
=> Fix(CCOM 280) - Add onChange Callback

.storybook/main.js
This config its to generate a stories.json file in the storybook build. This file should improve the perfomance when quantum is imbedded in the CC storybook.
=> chore(Main storybook): Adding config to the main storybook so it generates the stories.json file

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-340
=> feat(QTM-340): Adding security icon

components/AutoComplete/AutoComplete.jsx, components/index.d.ts, stories/AutoComplete/AutoComplete.story.jsx
The function normalizeChars, needs that the value informed is in lower case.
Before
After
=> fix(AutoComplete): Fixing function that filters the suggetion with user typed value

components/Alert/Alert.jsx, components/Alert/index.d.ts
https://jirasoftware.catho.com.br/browse/QTM-345
=> Fix(QTM-345) Alert: Corrige callback onClose e atualiza TS

components/Icon/Icon.jsx, components/Icon/index.d.ts, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-348
=> feat(Icon): adds wallet icon

components/Icon/Icon.jsx, components/shared/icons.js
=> fix(Chat Icon): adds new icon Chat

components/AutoComplete/index.d.ts, components/Skeleton/index.d.ts, components/TabbedView/index.d.ts
fix ts files from Skeleton, TabbedView, AutoComplete
=> fix(components types): fix ts files from Skeleton, TabbedView, AutoComplete

components/AutoComplete/index.d.ts
improvement component AutoComplete add placeholder
=> improvement(component add placeholder): improvement component AutoComplete add placeholder

components/TextArea/TextArea.jsx, components/TextArea/index.js, stories/TextArea/TextArea.story.jsx
BREAKING CHANGE: Changed ref in TextArea component
Reference to DOM input element
=> fix(TextArea.jsx): Forward reference adjustments in TextArea component

stories/Avatar/Avatar.stories.jsx, stories/Avatar/Avatar.story.mdx
https://jirasoftware.catho.com.br/browse/QTM-365
=> docs(QTM-365): updates documentation template

components/Icon/Icon.jsx, components/shared/icons.js
=> feat(Icon.jsx): Included filled favorite icon

components/Checkbox/__snapshots__/Checkbox.unit.test.jsx.snap, components/Checkbox/__snapshots__/CheckboxGroup.unit.test.jsx.snap, components/Dropdown/Dropdown.jsx, components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap, components/GlobalStyle/sub-components/__snapshots__/Title.unit.test.jsx.snap, components/Input/__snapshots__/Input.mask.unit.test.jsx.snap, components/Modal/__snapshots__/Modal.unit.test.jsx.snap, components/Popover/__snapshots__/Popover.unit.test.jsx.snap, components/RadioGroup/__snapshots__/RadioButton.unit.test.jsx.snap, components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap, components/Skeleton/__snapshots__/Skeleton.unit.test.jsx.snap, components/Tag/__snapshots__/Tag.unit.test.jsx.snap, components/TextArea/__snapshots__/TextArea.unit.test.jsx.snap, components/Toggle/__snapshots__/Toggle.unit.test.jsx.snap, package.json, yarn.lock
https://jirasoftware.catho.com.br/browse/QTM-408
=> chore(QTM-408): Fixed styled-components version

components/AutoComplete/AutoComplete.jsx, components/Checkbox/__snapshots__/Checkbox.unit.test.jsx.snap, components/Checkbox/__snapshots__/CheckboxGroup.unit.test.jsx.snap, components/Dropdown/Dropdown.jsx, components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap, components/GlobalStyle/sub-components/__snapshots__/Title.unit.test.jsx.snap, components/Input/__snapshots__/Input.mask.unit.test.jsx.snap, components/Modal/__snapshots__/Modal.unit.test.jsx.snap, components/Popover/__snapshots__/Popover.unit.test.jsx.snap, components/RadioGroup/__snapshots__/RadioButton.unit.test.jsx.snap, components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap, components/Skeleton/__snapshots__/Skeleton.unit.test.jsx.snap, components/Tag/__snapshots__/Tag.unit.test.jsx.snap, components/TextArea/__snapshots__/TextArea.unit.test.jsx.snap, components/Toggle/__snapshots__/Toggle.unit.test.jsx.snap, package.json, yarn.lock
https://jirasoftware.catho.com.br/browse/QTM-407
=> fix(autocomplete): erases filtered suggestions when clear button is clicked

components/Pagination/Pagination.jsx, components/Pagination/Pagination.unit.test.jsx, components/Pagination/index.d.ts, components/Pagination/sub-components/Desktop.jsx, components/Pagination/utils/pagination.js, components/Pagination/utils/pagination.unit.test.js, stories/Pagination/Pagination.regression-test.story.jsx
https://jirasoftware.catho.com.br/browse/QTM-415
=> fix(QTM-415):  Update ts file with new property to hide last page

components/Icon/Icon.jsx, components/shared/icons.js
https://jirasoftware.catho.com.br/browse/QTM-417
=> feat(Icon.jsx): Inserted Help icon

components/DropdownLight/DropdownLight.unit.test.jsx
https://jirasoftware.catho.com.br/browse/QTM-428
=> (QTM-428)Improved test coverage for DropDown Light

.github/workflows/actions-development.yml, .github/workflows/actions-publish.yml
https://jirasoftware.catho.com.br/browse/qtm-423
=> build: (QTM-423) - updated node and environment files in pipeline

components/Checkbox/Checkbox.jsx, components/Checkbox/__snapshots__/Checkbox.unit.test.jsx.snap, components/Checkbox/__snapshots__/CheckboxGroup.unit.test.jsx.snap, components/Checkbox/index.d.ts
https://jirasoftware.catho.com.br/browse/QTM-437
=> fix(QTM-437):  Link overlaps label content

MAINTAINERS.md
This pr seeks to validate the quantum publication process in npm, as requested by Celestino
=> feat: publish test

components/DropdownLight/DropdownLight.jsx, components/DropdownLight/DropdownLight.unit.test.jsx, components/DropdownLight/index.d.ts, stories/DropdownLight/DropdownLight.stories.jsx, stories/DropdownLight/DropdownLight.story.mdx
https://jirasoftware.catho.com.br/browse/QTM-190
=> (QTM-190) - DropdownLight Implemented selectedItem, onChange

README.md
=> fix(README.md): Added dot on text

components/GlobalStyle/sub-components/Typography.jsx, components/GlobalStyle/sub-components/__snapshots__/Typography.unit.test.jsx.snap
https://jirasoftware.catho.com.br/browse/QTM-444
=> perf: (QTM-444) preload on font loading

yarn.lock
https://jirasoftware.catho.com.br/browse/QTM-425
=> build(yarn.lock): Updated http-cache-semantics to 4.1.1 version

CONTRIBUTING.MD
https://jirasoftware.catho.com.br/browse/QTM-448
=> Updates (Contributing.MD) structure

components/Input/index.d.ts, components/Modal/index.d.ts
https://jirasoftware.catho.com.br/browse/QTM-442
Script for tests:
1. Yarn Build (QTM-442)
2. Choose some other project that uses typescript
3. Open the package.json file
4. Change the Quantum CDN path to the location pointing to the Quantum build folder
=> (Input/modal) QTM-442 - Problems with compounded components and intellisense

components/AutoComplete/SubComponents/UseKeyPress.jsx
https://jirasoftware.catho.com.br/browse/QTM-461
=> (Autocomplete) QTM-461 - UseKeyPress being called multiple times

scripts/create-component.js
https://jirasoftware.catho.com.br/browse/QTM-445
Help: 
1. run script `yarn generate YourComponente`
2. open Storybook and validate
=> (QTM-445) Fixed export script yarn generate

CONTRIBUTING.MD
https://jirasoftware.catho.com.br/browse/QTM-449
=> Doc (QTM-449) Updates Contrbuting File [Updates the steps to create a new component]

CONTRIBUTING.MD
https://jirasoftware.catho.com.br/browse/QTM-450
=> docs(documentation): QTM-450 - Editing an existing component

CONTRIBUTING.MD
https://jirasoftware.catho.com.br/browse/QTM-443
=> QTM-443 (Doc) Updates Contributing.md file

components/Grid/sub-components/Row.jsx, components/Grid/sub-components/Row.unit.test.jsx
https://jirasoftware.catho.com.br/browse/QTM-479
Clone the project recruiter-experience_company-registration (https://github.com/catho/recruiter-experience_company-registration_app/tree/development) and checkout to branch `development`
**In quantum project...**
- Make the build (Run `yarn` & `yarn build`).
**In the recruiter-experience_company-registration project ...**
- Add the quantum build you made earlier by running `yarn add [path-to-quantum-build]`;
- Place a conditional to render the first Col component of the FormRegistrationData component (line 132 of the src/components/Forms/FormRegistrationData/index.tsx file)
- Run  `yarn` & `yarn dev`
- In the browser, I checked that the form rendered correctly
=> fix(Row.jsx): Validating and handling all child types before rendering them

components/Grid/sub-components/Row.unit.test.jsx, yarn.lock
https://jirasoftware.catho.com.br/browse/QTM-477
observation: I noticed that a warning about the key in the Row component was present in the master when running the unit tests. As this is not something complex, decide to adjust this pr
=> chore(QTM-477): Updated yarn.lock

components/DropdownLight/DropdownLight.jsx, components/DropdownLight/DropdownLight.unit.test.jsx, components/DropdownLight/SubComponents/UseKeyboardSearchItems.jsx, stories/DropdownLight/mock.js
https://jirasoftware.catho.com.br/browse/QTM-495
=> feat(QTM-495):  Navigating between items using letter keys

components/Checkbox/CheckboxGroup.jsx
https://jirasoftware.catho.com.br/browse/QTM-526
There were no unnecessary renderings in the component. I took the opportunity to migrate it to a functional component. Therefore, the review basically consists of checking whether the checkboxes are being checked and unchecked correctly and whether the item values ​​are being updated as the component is clicked. This last point can be validated through the Controlled example from the CheckboxGroup documentation (yarn storybook)
=> refactor(CheckboxGroup.jsx): Transformed into functional component

stories/SnackBar/SnackBar.mdx, stories/SnackBar/SnackBar.stories.jsx
https://jirasoftware.catho.com.br/browse/QTM-520
It was not necessary to make the component more flexible, as foreseen in the task. However, it was necessary to include a new example of using the component. Check if the new example is good
=> docs(QTM-520): Added new example with text element

components/TabbedView/TabbedView.jsx, components/TabbedView/TabbedView.unit.test.jsx, components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
https://jirasoftware.catho.com.br/browse/QTM-531
When testing the documentation, test the fluid prop with 1, 2 or more than 3 tabs to verify that the width of the tabs is fitting correctly
=> fix(QTM-531): Fixed display of tabs when prop fluid is true

yarn.lock
https://jirasoftware.catho.com.br/browse/QTM-551
=> chore(QTM-551): updated yarn.lock

components/Checkbox/Checkbox.jsx, components/Checkbox/__snapshots__/CheckboxGroup.unit.test.jsx.snap, stories/Checkbox/CheckboxGroup.stories.jsx
https://jirasoftware.catho.com.br/browse/QTM-553
=> feat(Checkbox.jsx): Inline view of Checkbox group component when type is checkbox

stories/Grid/Grid.jsx, stories/Grid/Grid.mdx
https://jirasoftware.catho.com.br/browse/QTM-578
=> docs(Grid.mdx): Adding descriptive text of offset prop usage with multiple columns

.gitignore
PR made to publish new version of quantum to make clicked tab available from the TabbedView component
=> feat: Ignored git cache and temp folders

stories/Colors/Colors.mdx, stories/Grid/Grid.mdx, stories/Typography/Typography.mdx
Description
https://jirasoftware.catho.com.br/browse/QTM-604
Setup
to view the components behavior, run yarn storybook
then check the referred components documentation
Review guide
=> docs[QTM-604] Includes EvaluationForm in Colors, Grid and Typography

stories/Breakpoints/Breakpoints.mdx, stories/Colors/Colors.mdx, stories/Grid/Grid.mdx, stories/Icon/Icon.mdx, stories/Link/Link.mdx, stories/List/List.mdx, stories/Theme/Theme.mdx, stories/Typography/Typography.mdx
Description
https://jirasoftware.catho.com.br/browse/QTM-609
Setup
to view the components behavior, run yarn storybook
then check the referred components documentation
Review guide
=> docs [QTM-609] Includes EvaluationForm in Link and List

stories/Alert/Alert.mdx, stories/Avatar/Avatar.mdx, stories/Badge/Badge.mdx, stories/Breadcrumbs/Breadcrumbs.mdx, stories/Button/Button.mdx, stories/Button/SocialButton.mdx, stories/Card/Card.mdx, stories/Carousel/Carousel.mdx, stories/ChargeBar/ChargeBar.mdx, stories/Dialog/Dialog.mdx, stories/Hamburger/Hamburguer.mdx, stories/Loaders/CircularLoader.mdx, stories/Loaders/ProgressBar.mdx, stories/Loaders/Skeleton.mdx, stories/Modal/Modal.mdx, stories/Pagination/Pagination.mdx, stories/Popover/Popover.mdx, stories/Score/Score.mdx, stories/SegmentedControl/SegmentedControl.mdx, stories/SnackBar/SnackBar.mdx, stories/Socials/Socials.mdx, stories/Stepper/Stepper.mdx, stories/TabbedView/TabbedView.mdx, stories/Tag/Tag.mdx, stories/Tooltip/Tooltip.mdx
Description
https://jirasoftware.catho.com.br/browse/QTM-625
Setup
to view the components behavior, run yarn storybook
then check the referred components documentation
Review guide
=> docs: [QTM-625] Includes EvaluationForm in remaining components

.gitignore
Created to publish a new version containing the new icons added in the PR https://github.com/catho/quantum/pull/549
=> feat: Updated .gitignore

CONTRIBUTING.MD, README.md
https://jirasoftware.catho.com.br/browse/QTM-698
=> docs(QTM-698): Inclusion in the docs of the suggestion not to use MUI in implem

components/Badge/Badge.jsx, components/Badge/Badge.module.css, components/Badge/Badge.unit.test.jsx, components/Badge/__snapshots__/Badge.unit.test.jsx.snap, components/Badge/index.css, components/Badge/index.d.ts, components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap, components/index.css, components/shared/theme.d.ts, components/shared/theme.js
https://jirasoftware.catho.com.br/browse/QTM-650
=> feat(QTM-650): Converted styles from styled components to CSS modules

CONTRIBUTING.MD
=> feat: Updates Contributing.md
