catho/quantum

components/TabbedView/TabbedView.jsx
components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap

When there are title with accents and space in `<Tab />`, they're set in attributes in the elements.
This pull request removes spaces and accents. It will replace space with "-" too.

[FIX] Sanitize title in using HTML attributes in <TabbedView />

---

components/List/__snapshots__/List.unit.test.jsx.snap
components/List/sub-components/__snapshots__/Content.unit.test.jsx.snap
components/List/sub-components/__snapshots__/Header.unit.test.jsx.snap
components/List/sub-components/__snapshots__/Item.unit.test.jsx.snap
components/List/sub-components/__snapshots__/SubHeader.unit.test.jsx.snap
components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
yarn.lock

```
BEFORE:
1759 vulnerabilities found - Packages audited: 73939
Severity: 64 Low | 10 Moderate | 1684 High | 1 Critical
lodash
1759 vulnerabilities found - Packages audited: 73939
Severity: 64 Low | 10 Moderate | 1684 High | 1 Critical
jest
127 vulnerabilities found - Packages audited: 74657
Severity: 64 Low | 9 Moderate | 53 High | 1 Critical
enzyme
126 vulnerabilities found - Packages audited: 74810
Severity: 64 Low | 9 Moderate | 52 High | 1 Critical
commitizen
94 vulnerabilities found - Packages audited: 74810
Severity: 64 Low | 9 Moderate | 20 High | 1 Critical
eslint
89 vulnerabilities found - Packages audited: 74811
Severity: 64 Low | 7 Moderate | 18 High
AFTER:
lint-staged
77 vulnerabilities found - Packages audited: 74809
Severity: 64 Low | 1 Moderate | 12 High
```

fix: Upgrade libs to remove vulnerabilities

---

components/Input/Input.jsx

closes #134 
Adds a parameter `event` to `onChange` function on `Input` component.
Today we cannot get the event props in `onChange` function prop.

fix(input): adds parameter to onchange function on input component

---

components/Hamburger/Hamburger.jsx

In hamburger component was left a console log behind. This console is showing in unit tests loads.

test(Hamburger): removes console on component

---

components/Grid/sub-components/Col.jsx

https://jirasoftware.catho.com.br/browse/QTM-150
⚠️  resolves issue https://github.com/catho/quantum/issues/179
- compare the alignments of the Grid in this branch with the production : https://catho.github.io/quantum/?path=/story/foundation--grid-system
- Simulate a new aplication it implements the Quantum Grid and test in Edge 15

fix(QTM-150): fixes the display grid fallback in Edge 15

---

components/Dropdown/Dropdown.jsx
components/Dropdown/Dropdown.unit.test.jsx
components/shared/index.js
components/shared/normalizeChars.js
components/shared/normalizeChars.unit.test.js
stories/Dropdown/Dropdown.story.jsx
stories/Dropdown/examples.jsx

The current version of the component Dropdown when used how autocomplete don't return list if input is not identical, exemple with a itens list how [ 'são paulo',  'belém'] just return if input is 'são paulo' or 'belém'.
With this parameter "ignoreSpecialChars" we can input 'sao paulo' and return list the suggest corrctly.
Changes list:
* Add new parameter in Dropdown component
* Create a function to remove special chars inside the Dropdown component
* Add unit test for Dropdown autocomplete with and without new prop
* Add new parameter in doc storybook 

feat(Dropdown): Add property to ignore special chars

---

components/shared/normalizeChars.js
components/shared/normalizeChars.unit.test.js

Just add new char to be normalize.
Add new pattern to remove chars unwanted.
Created new unit test
- [x ] Unit tests (yarn test:components)

feat(normalize-char): Add new char in normalizeChars function

---

components/GlobalStyle/sub-components/Typography.jsx
components/Modal/Modal.jsx
components/Pagination/Pagination.jsx
components/shared/isSSR.js
components/shared/isSSRRender.js

When the Modal is open, the background must be blocked in scroll or tap events.
https://jirasoftware.catho.com.br/browse/QTM-164

fix(Modal): locks scroll when modal is open

---

components/RadioGroup/Radio.jsx
components/RadioGroup/Radio.unit.test.jsx
components/RadioGroup/__snapshots__/Radio.unit.test.jsx.snap
components/RadioGroup/index.d.ts
stories/RadioGroup/RadioGroup.story.jsx
stories/RadioGroup/sub-components/childrenRadio.jsx
stories/RadioGroup/sub-components/index.jsx

When we were using `<RadioGroup.Radio />` with HTML element inside that, this error in console occurred:
This PR, adjust component to use `string` or elements inside `<RadioGroup.Radio />`

[Refactor] Adding children as string or elements in the <RadioGroup.Radio />

---

components/Card/sub-components/Thumbnail.jsx

task: https://jirasoftware.catho.com.br/browse/QTM-178
Issue: https://github.com/catho/quantum/issues/130
⚠️ this new attribute only will show in the <img /> when the styled-components is updated.
In actual version `4.1.3`, this attribute did not exist and the styled removes the attributes that not recognise.
But, with this PR, when the styled-components is update, the attribute will show and works.
The problem in styled was solved here https://github.com/styled-components/styled-components/issues/2552

feat(Card Thumbnail): implements native lazy load

---

components/Accordion/__snapshots__/Accordion.unit.test.jsx.snap
components/Alert/__snapshots__/Alert.unit.test.jsx.snap
components/Button/__snapshots__/Button.unit.test.jsx.snap
components/Checkbox/__snapshots__/Checkbox.unit.test.jsx.snap
components/Checkbox/__snapshots__/CheckboxGroup.unit.test.jsx.snap
components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap
components/Icon/Icon.jsx
components/Icon/__snapshots__/Icon.unit.test.jsx.snap
components/Input/__snapshots__/Input.mask.unit.test.jsx.snap
components/Modal/__snapshots__/Modal.unit.test.jsx.snap
components/Popover/__snapshots__/Popover.unit.test.jsx.snap
components/RadioGroup/__snapshots__/RadioButton.unit.test.jsx.snap
components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
components/Tag/__snapshots__/Tag.unit.test.jsx.snap
components/Toggle/__snapshots__/Toggle.unit.test.jsx.snap

This occurs because the css of the material loads after the render of svgs.
To avoid this, was putted a default size (0px) on pre loading process, for the svg icons doesnt break the layout.
⚠️ If your testing in catho-components, the icons still are loading in the wrong way, update the Quantum in node_modules of catho-components with the last build you made
To simulate, build the Quantum and import in another application.

fix(Icons): make a default icon size on pre loading

---

components/Pagination/Pagination.jsx
components/Pagination/Pagination.unit.test.jsx
stories/Pagination/Pagination.story.jsx
stories/Pagination/examples/ControlledPagination.jsx

This change allow all user of the Quantum to receive event of the onclick in handler function pass by the prop "onPageClick"

feat(Pagination): Allow onClick event return in onClick handler function

---

package.json

build(dependencies): Moving quantum-storybook-ui to devDependencies

---

components/RadioGroup/Radio.jsx
components/RadioGroup/__snapshots__/Radio.unit.test.jsx.snap
components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap

fix(Radio button): fixes the text align when the label breaks line

---

components/RadioGroup/RadioGroup.jsx
components/RadioGroup/RadioGroup.unit.test.jsx
stories/RadioGroup/RadioGroup.story.jsx
stories/RadioGroup/sub-components/propsRadioGroup.jsx

https://jirasoftware.catho.com.br/browse/QTM-215

fix(RadioGroup): use defaultChecked for predefined radio group values

---

components/Card/index.d.ts
components/Modal/index.d.ts

Adding `onClick` in the `<Card />` type to avoid Typescript error when use it.
This PR sort out issue #220 
1. create a new folder _quantum_ in _node_modules/@catho in the your Typescript (TS) project
2. in Quantum's project, run `yarn run build`
3. copy folder _dist_ to project path (ex.: `cp -r dist/ ~/projects/new-register-candidate_app/node_modules/@catho/quantum/
Adding in your TS project this:
```
<Card onClick={(e): void => console.log('foo and bar', e)}>
<Card.Content>
Duis ac enim non leo dapibus placerat ut vel ligula. Pellentesque sed
metus elit. In hac habitasse platea dictumst. Fusce non purus a dui
semper molestie vitae in sapien. In a odio quis nisi placerat varius
eget et magna. Donec nec cursus mauris. Donec a cursus velit.
</Card.Content>
</Card>
```

Updating Cards and Modal type

---

components/RadioGroup/Radio.jsx
components/RadioGroup/Radio.unit.test.jsx
components/RadioGroup/RadioGroup.jsx
components/RadioGroup/RadioGroup.unit.test.jsx
components/RadioGroup/__snapshots__/Radio.unit.test.jsx.snap
components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap

Was added a property required to the component Radio and RadioGroup.
That need came because we need valid radio as "required" in form and didn't have that prop before.

feat(required-radio-group): Add property "required" to the RadioGroup component

---

components/index.js

This PR fixes to component should be imported this way `import { Avatar } from '@catho/quantum'` or this way `import Avatar from '@catho/quantum/Avatar'`
The individual export of component is missing.
when imports `import { Avatar } from '@catho/quantum'`, this error was shown:
The component only imports this way `import Avatar from '@catho/quantum/Avatar';`

fix(Avatar): Fixes export default

---

components/Avatar/Avatar.jsx
components/Avatar/__snapshots__/Avatar.unit.test.jsx.snap

The Avatar component, in some cases, need to be clicked as trigger to open menu options.
For this cases, the svg icons needs a `pointer-events: none` to the mouse click works right.
Without it,  the click field gets harmed. 

fix(Avatar): updates svg pointer-events

---

components/Input/Input.jsx
components/Input/Input.unit.test.jsx

This PR fixes the problem of **updating the Input text** when a new string is defined in the `value` property after the first render.
**Related issue: #245**
to view the component's behavior, run `yarn storybook`

fix(Input): update state when value prop is changed

---

.github/workflows/actions-publish.yml
stories/Avatar/Avatar.story.jsx

ci(deploy to gh pages): removes gh_token to use only github_token

---

.github/workflows/actions-publish.yml

ci(deploy ghpages): removes github_token and keep only gh_token

---

components/Stepper/__snapshots__/Stepper.unit.test.jsx.snap
components/Stepper/style.js

Fixes the min width in desktop.

fix(Stepper component): fixes min-width for desktop

---

components/Tag/Tag.jsx
components/Tag/index.d.ts

https://jirasoftware.catho.com.br/browse/QTM-262
Today, the component only checks if the prop is a string. This PR updates to receive a html element either.

fix(Tags component): updates proptypes to receive elements instead only strings

---

components/Carousel/Carousel.unit.test.jsx
components/Carousel/watchMedia.mock
jest-config.js

because the import of react-slick in carousel component, jest needs to watchMedia to monitoring it.
Error: 
This erros was fixed adding this code in jest-config:
```
if (typeof window !== 'undefined') {
// eslint-disable-next-line func-names
window.matchMedia =
window.matchMedia ||
function() {
return {
matches: false,
addListener() {},
removeListener() {},
};
};
}
```
But with this, who implements Quantum, this error will show, because its application doesnt have this code in your jest-config file.
To fix this issue, i import this code only in carousel unit test, with this, this code will be exported even with babel transpilling.
there being no need to implement this code in applications.
**sorry for many codes word in description**

fix(Carousel component): fixes watch media mock in jest

---

components/index.js
stories/Carousel/Carousel.story.jsx

because of [react-slick lib](https://react-slick.neostack.com/), is necessary to implement a [snippet of code](https://github.com/akiran/react-slick/issues/742#issuecomment-460281987) in its unit tests.
WIth that, all implementers that import Quantum, will be necessary to put this code in your Jest configurations.
This PR removes the Carousel component of its index and update doc of carousel in storybook. 
With it, Quantum does not break tests, only the implementers has Carousel in its tests. In this case, will be necessary
to put the code demonstrated in carousel component doc.

fix(Carousel component): removes carousel of index of components

---

components/Dropdown/index.d.ts
components/Form/index.d.ts

- Dropdown:
the ts props of component has missing `name` prop.
- Form
Some implementers having problems when uses native form attributes in component.

fix(Typescript compatibility): updates ts props in components

---

package.json
yarn.lock

https://github.com/catho/quantum/security/dependabot/yarn.lock/property-expr/open
the dependency was used in yup dep., which in turn was used in lint-staged@8.3.1.
The lint-staged@11.0.0 dont uses property-expr.

fix(Security updates): updates lint-staged (property-expr dep security problem)

---

components/Alert/__snapshots__/Alert.unit.test.jsx.snap
components/Badge/__snapshots__/Badge.unit.test.jsx.snap
components/Button/Button.jsx
components/Button/__snapshots__/Button.unit.test.jsx.snap
components/Form/__snapshots__/Form.unit.test.jsx.snap
components/Modal/__snapshots__/Modal.unit.test.jsx.snap
components/Popover/__snapshots__/Popover.unit.test.jsx.snap
components/SegmentedControl/__snapshots__/SegmentedControl.unit.test.jsx.snap
components/SocialButton/__snapshots__/SocialButton.unit.test.jsx.snap

Due to not using css property with styled components in the button component, we had a few parsing errors in the snapshots
when running test coverage 
It was removed a piece of code from the button component, because the code it self only started working after the changes and it was not necessary any more.  

test(TestCoverage): Fixing parsing error when using test coverage

---

components/Accordion/Accordion.jsx
components/Accordion/__snapshots__/Accordion.unit.test.jsx.snap

Fixing clickable area in links due to Accordion being used in the footer
https://jirasoftware.catho.com.br/browse/CCOM-89

fix(CCOM-89-Accordion): Fixing clickable area for links

---

components/Icon/index.d.ts

Includes person_circle icon on TS definitions

fix(icon): Includes person_circle icon on TS definitions

---

components/shared/helpers.js
components/shared/hooks/UseMaxWidthMediaQuery/useMaxWidthMediaQuery.jsx
components/shared/hooks/UseMaxWidthMediaQuery/useMaxWidthMediaQuery.unit.test.jsx
jest-config.js
stories/Hooks/Examples/UseMaxWidthMediaQueryExample.jsx

fix(UseMaxWidthMediaQuery): Implementing support to safari and adding mock to jest config 

---

components/SocialButton/SocialButton.jsx

Rolling back a change made [here](https://github.com/catho/quantum/pull/380) due to error in the quantum ui auto example 

fix(Social Button): rollback on a change due to quantum ui auto example error

---

components/Stepper/__snapshots__/Stepper.unit.test.jsx.snap
components/Stepper/style.js

https://jirasoftware.catho.com.br/browse/QTM-346

fix(Stepper): corrige resolução do componente em 1024+

---

components/TextArea/TextArea.jsx
components/TextArea/TextArea.unit.test.jsx

Same was done with Input (https://github.com/catho/quantum/pull/369).
Now in Textarea component too.

fix(TextArea): fixes the current update state

---

components/AutoComplete/AutoComplete.jsx

https://jirasoftware.catho.com.br/browse/QTM-351
https://watch.screencastify.com/v/4jtLRBnBCfV7N0jBzHOq

fix(QTM-351): Adjusts on handle click outside

---

components/AutoComplete/AutoComplete.jsx
components/AutoComplete/AutoComplete.unit.test.jsx
components/AutoComplete/index.d.ts

https://jirasoftware.catho.com.br/browse/QTM-468
- In quantum, run `yarn` & `yarn build`
- Clone repo https://github.com/catho/recruiter-experience_company-registration_app/tree/development
- Add an .env file in the root of the repository with the data provided in the task in Jira
- Run `yarn add ~/quantum/dist`, `yarn ` & `yarn dev`
- Add the value={values.role} attribute to the AutoComplete component on line 145 of the src/components/Forms/FormRegistrationData/index.tsx file
- On the application page in the browser, fill in all the data in the form in the first step and click on the "Continuar" button and then on "Voltar".
- Check if the "Cargo" field has preserved the previously entered value

feat(QTM-468): Added property to set an initial value for autocomplete

---

components/Checkbox/CheckboxButton.jsx
components/Dropdown/Dropdown.jsx
components/Input/Input.jsx
components/Pagination/sub-components/Desktop.jsx
components/RadioGroup/RadioButton.jsx
components/SegmentedControl/SegmentedButton.jsx
components/SnackBar/SnackBar.jsx
components/TextArea/TextArea.jsx
components/shared/index.js
components/shared/uniqId.js
package.json
yarn.lock

Closes #147 
This PR refactors the existing code that generates unique IDs to a new implementation using a closure. This refactor provides better performance and eliminates the need for the **babel-polyfill** dependency.

Refactor uniqId generator to improve performance and remove babel-polyfill dependency

---

components/Icon/Icon.jsx
components/shared/icons.js

https://jirasoftware.catho.com.br/browse/QTM-485

QTM-485: Adds flash_on icon

---

components/Hamburger/Hamburger.jsx
components/Hamburger/__snapshots__/Hamburger.unit.test.jsx.snap

This PR refactors Hamburger and make it use Icon component instead of import icons directly from @material-ui/icons

refactor: make Hamburger use Icon component

---

CONTRIBUTING.MD
scripts/templates/component-story.js
scripts/templates/component.js

https://jirasoftware.catho.com.br/browse/QTM-528
Open the Terminal and Create a new component with the command line:
`yarn generate <NewComponent>`
_Make sure to name the component using Pascal Case, or at least starting the name with a capital letter._
Check the created component at `./components/<NewComponent>` and `./stories/<NewComponent>`
There should be seven new files:
- at ./components/<NewComponent>
1. index.d.ts
2. index.js
3. <NewComponent>.jsx
4. <NewComponent>.unit.test.jsx
-  at /stories/<NewComponent>
1. <NewComponent>.mdx
2. <NewComponent>.regression-test.story,jsx
3. <NewComponent>.stories.jsx
Run `yarn storybook` and check if the <NewComponent> is listed.
Run Regression Tests to update the references. 
Run `yarn build` to build Quantum Dist.
Open an application that uses …

fix[QTM-528] Fixes Create a Component script

---

components/AutoComplete/AutoComplete.jsx
components/AutoComplete/AutoComplete.unit.test.jsx

https://jirasoftware.catho.com.br/browse/QTM-527
Connect to VPN
Download the project https://github.com/catho/recruiter-experience_company-registration_app and use the latest version of the "main" branch.
Add an .env file to the project root with the correct data (ask @MarcosViniciusPC )
Install version 18 of node. Ex: `nvm install 18.16.1`
Change the node version to the previously installed version. Ex: `nvm use 18.16.1`
Download dependencies: yarn
Run the application: yarn dev
In the first step of registration, navigate using the tab to the "Job Role" field, type "desen" and select any suggested option
Wait 2 seconds (until the list of options appears again)
Press the "down" arrow key on the keyboard
In quantum, install the dependencies and build: `yarn && yarn build`.
In the project …

fix(QTM-527): Fixing navigation between items using keyboard

---

stories/Accordion/Accordion.mdx
stories/Breakpoints/Breakpoints.mdx
stories/Colors/Colors.mdx
stories/Grid/Grid.mdx
stories/Hooks/Hooks.mdx
stories/Icon/Icon.mdx
stories/InfiniteScroll/InfiniteScroll.mdx
stories/Link/Link.mdx
stories/List/List.mdx
stories/Theme/Theme.mdx
stories/Typography/Typography.mdx

Description
https://jirasoftware.catho.com.br/browse/QTM-613
Setup
to view the components behavior, run yarn storybook
then check the referred components documentation
Review guide

docs [QTM-613] Includes EvaluationForm in  Infinite Scroll, Hooks/useMaxWithMediaQuery & Accordion

---

.github/workflows/actions-publish.yml

https://jirasoftware.catho.com.br/browse/QTM-598

ci(Configuring publishing pipeline to run when there is a merge into the beta branch and skipping publishing in that case)

---

.babelrc
components/index.css
jest-config.js
package.json
postcss.config.js
scripts/JestCSSModulesSerializer/buildCss.js
scripts/JestCSSModulesSerializer/index.js
scripts/JestCSSModulesSerializer/styleSheetSerializer.js
scripts/babel-css-modules.js
scripts/copy-files.js
scripts/injectCssInDocument.js
yarn.lock

https://jirasoftware.catho.com.br/browse/QTM-599
https://jirasoftware.catho.com.br/browse/QTM-597
NOTE: 
- Following the guidelines below, it is expected that Button snapshot tests will break due to the CSS styling that is applied to the component.
- In regressive testing, documentation and build testing, it is expected that the component will be rendered correctly. When inspecting the component on the page, it is possible to see the CSS styles being applied to the component, but they are not necessary working, as the styled components styles have a higher priority
1. Create a css file to style the Button component in the respective component folder.
Ex: /quantum/components/Button/Button.module.css
2. In the css file, do some styling.
Ex:
`.test {
color: aquamarine;
}`
3. In the …

build(QTM-597): Build css and save css styles in jest snapshots

---

components/Carousel/__snapshots__/Carousel.unit.test.jsx.snap
components/Carousel/sub-components/DescriptionCard.jsx
components/Carousel/sub-components/ThumbCard.jsx
components/Carousel/sub-components/__snapshots__/CarouselCard.unit.test.jsx.snap
components/Modal/Modal.jsx
components/Modal/__snapshots__/Modal.unit.test.jsx.snap
components/Modal/sub-components/Content.jsx
components/Modal/sub-components/Header.jsx
components/Modal/sub-components/Title.jsx

https://jirasoftware.catho.com.br/browse/QTM-696

chore(QTM-696): Avoiding passing props from the Carousel and Modal components to the Card component

---

components/Icon/Icon.jsx
components/shared/icons.js

Add lightbulb outlined icon
To view the components behavior, run `yarn storybook`

feat(icon): add lightbulb_outlined icon

---

components/Icon/Icon.jsx
components/shared/icons.js

feat(icon): adds more_vert icon

---

components/Icon/Icon.jsx
components/Icon/index.d.ts
components/shared/icons.js

Icon used in https://github.com/catho/help_help-center_app. Currently the application uses this icon directly from the @material-ui/icons lib, which has a dependency on the @material-ui/core lib. The latter was not added to the project as it is used directly from the version of quantum currently installed in the application. As the latest version of quantum no longer contains the @material-ui/core lib, the application breaks when updating the quantum version. By adding this icon here, the application works again

feat(Icon.jsx): Added ContactSupport icon

---

.github/workflows/actions-development.yml
.github/workflows/actions-publish.yml

https://jirasoftware.catho.com.br/browse/QTM-666

ci(QTM-666): Updated actions/checkout and setup-node to node v20 support

---

components/Icon/Icon.jsx
components/Icon/index.d.ts
components/shared/icons.js

[JAS-4013](https://jirasoftware.catho.com.br/browse/JAS-4013)

feat(JAS-4013): add new icon to Cathoflix category

---

components/Icon/Icon.jsx
components/Icon/index.d.ts
components/shared/icons.js

Adding DescriptionOutlinedIcon

feat: adding new icon (DescriptionOutlinedIcon)

---

components/Button/Button.jsx
components/Button/Button.unit.test.jsx
components/Button/__snapshots__/Button.unit.test.jsx.snap

It was identified that the disabled prop that is passed to the component was being used only for aesthetic purposes and was not being passed to the button element, thus impacting the accessibility of the component. To test, access the regressive test, select button-disabled and check if the disabled attribute is present in the element through the DOM tree

fix(Button.jsx): Forwarding disabled prop to button component

---

components/TabbedView/TabbedView.jsx
components/TabbedView/TabbedView.unit.test.jsx

related to: https://github.com/catho/quantum/issues/584
- Transformation of the component from class component into functional component
- Enhancement of the component `<TabView />` so could be able to change the current tab from another component. Example above:
(this example was taken from `recruiter-onboarding_recruiter-account_app/src/components/TabView/index.tsx`)

Update TabView Component to change tab when activeTab changes

---

components/Popover/Popover.jsx
components/Popover/Popover.unit.test.jsx
components/Popover/index.d.ts
components/Popover/sub-components/Content.jsx
stories/Popover/Popover.regression-test.story.jsx

https://jirasoftware.catho.com.br/browse/QTM-779

feat(QTM-779): Add close functionality when clicks on elements other than the popover

---

components/AutoComplete/AutoComplete.jsx
components/AutoComplete/AutoComplete.module.css
components/AutoComplete/__snapshots__/AutoComplete.unit.test.jsx.snap
components/AutoComplete/index.css
components/AutoComplete/index.d.ts
components/index.css

https://jirasoftware.catho.com.br/browse/QTM-728
- In quantum, install the dependencies and build, running `yarn && yarn build`
- Clone the repository https://github.com/catho/ssr-quantum-simulator
- In ssr-quantum-simulator, add the local quantum build using `yarn add [local-path]/quantum/dist`
- Change the GlobalStyle imports to Typography in the _app and quantum.js files.
- In the _app file, import the quantum css using `import '@catho/quantum/index.css'`
- Still in ssr-quantum-simulator, run `yarn dev` and access the page http://localhost:3000/quantum
- Compare components with …

feat(QTM-728): Migrated to css modules and updated types and snapshots

---

components/Alert/Alert.jsx
components/Alert/Alert.module.css
components/Alert/__snapshots__/Alert.unit.test.jsx.snap
components/Alert/index.css
components/Alert/index.d.ts
components/index.css
components/shared/theme.d.ts
components/shared/theme.js

https://jirasoftware.catho.com.br/browse/QTM-717

feat(QTM-717): Migrated to css modules

---

components/Popover/__snapshots__/Popover.unit.test.jsx.snap
components/Popover/arrowProperties.js

https://jirasoftware.catho.com.br/browse/QTM-402
The character was changed to its unicode (Ex: "25C0"). In some contexts, unicode must come after "\u", as this is a unicode code indicator. After the character unicode, a unicode variation "\uFE0E" was added, which forces rendering as text instead of emoji. the end result is \u25C0\uFE0E

fix(QTM-402): Correction in the display of emoji instead of the balloon position indicator arrow

---

components/DropdownLight/DropdownLight.jsx
components/DropdownLight/DropdownLight.unit.test.jsx
components/DropdownLight/SubComponents/UseKeyPress.jsx

https://jirasoftware.catho.com.br/browse/QTM-705

feat(QTM-705): Fix for focusing on other page elements when the "esc" key is pressed
